version: '2'

services:
  alertmanager:
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    ports:
      - '9093:9093'
